settings:
  title: 'Status Page'
  url: 'https://cf-workers-status-page-production.15130907875.workers.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '一切正常'
  notAllmonitorsOperational: '存在异常站点'
  monitorLabelOperational: '正在运行'
  monitorLabelNotOperational: '未运行'
  monitorLabelNoData: '暂无数据'
  dayInHistogramNoData: '暂无数据'
  dayInHistogramOperational: '一切正常'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: xwy-alist-mian
    name: xwy-alist-mian
    description: 'xwy的alist主站点'
    url: 'https://xwy231321.top'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

 - id: xwy-alist-other # unique identifier
    name: xwy-alist-other
    description: 'xwy阿里云上的alist副站点' # default=empty
    url: 'https://xwy231321.top:5243' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
